build.gradle, src/main/antlr/SHRLexer.g4, src/main/antlr/SHRParser.g4
This pull request brings in support for generating javascript parsers and lexers.  It also brings in a few minor corrections to the grammar.
To generate the javascript parsers to `/path/to/parsers`, issue the following gradle command:
```
gradle -Pshr.js.parsers.dir=/path/to/parsers generateAntlrJSGrammarSource
```
=> Javascript parsers

src/main/antlr/SHRParser.g4
Fix grammar to reflect that `Uses:` puts all used namespaces in a single comma-separated statement.  Also allow `Uses:` for value set def files.
=> Fix ANTLR4 grammar for 'Uses'

spec/shr_actor.txt, spec/shr_adverse.txt, spec/shr_allergy.txt, spec/shr_base.txt, spec/shr_demographics.txt, spec/shr_encounter.txt, spec/shr_familyhistory.txt, spec/shr_immunization.txt, spec/shr_lifehistory.txt, spec/shr_medication.txt, spec/shr_vital.txt, src/main/antlr/SHRLexer.g4, src/main/antlr/SHRParser.g4
Fixes bugs in the SHR text definitions based on errors discovered in parsing.  Also adds support for annotating TBD with a string, which allows us to export better documentation.
=> Grammar dec 2016 fixes

spec/shr_actor_map.txt, spec/shr_base.txt, spec/shr_core_map.txt, spec/shr_device_map.txt, spec/shr_encounter_map.txt, spec/shr_immunization_map.txt, spec/shr_lab.txt, spec/shr_lab_map.txt, spec/shr_medication.txt, spec/shr_medication_map.txt, spec/shr_observation_map.txt, spec/shr_procedure.txt, spec/shr_procedure_map.txt
Updates the definitions based on changes from FHIR 1.8.0 to FHIR 3.0.0.  This mainly deals with renamed FHIR properties and value sets.  More updates to come (to resolve mapping incompatibilities).
=> Initial FHIR 3.0.0 mapping updates

spec/shr_actor.txt, spec/shr_encounter.txt, spec/shr_encounter_vs.txt, spec/shr_lab.txt, spec/shr_lab_vs.txt, spec/shr_observation.txt
Several fixes relates to overriding extensible bindings in FHIR and/or trying to support two value sets bindings (FHIR only allows one at a time).
=> Fix Mis-Alignment w/ FHIR Extensible Bindings

spec/shr_behavior.txt, spec/shr_core.txt
**NOTE: All PR's into Flux-based branches require sign-off from multiple teams.  Please do not merge until sign-off is confirmed.**
This PR contains two fixes, neither of which should be considered risky to Flux:
**1) Fix invalid constraint path in IntravenousDrugUse**
The path `ObservationComponent.RouteIntoBody` is invalid because `RouteIntoBody` is not one of the types included in the `ObservationComponent` includes type constraints.  Changed it to `ObservationComponent.ExposureRoute`.
**2) Don't put card constraint on Numerator/Denominator Qaunatity/Units in Frequency**
Previously, the `Numerator` and `Denominator` constraints were:
```
1..1 Numerator.Quantity with units UCUM#1
1..1 Denominator.Quantity.Units with Coding from http://hl7.org/fhir/ValueSet/units-of-time
```
The problem …
=> Flux a spec fixes

config.json, spec/config.json, spec/shr_base.txt, spec/shr_behavior.txt, spec/shr_core.txt
These changes relate to issues that were encountered during the development of the JSON schema exporter or in support of Flux.  They represent the element definitions that were used to generate the schemas and ES6 classes that Flux is currently using.
In summary:
- Updated "example" config (inconsequential to Flux/SHR)
- Changed `Entry.EntryType` cardinality from `1..*` to `1..1`
- JSON was extremely verbose w/ whole type hierarchy encoded, and the type hierarchy can be easily inferred from the most specific type.
- Fixed `RouteIntoBody`/`ExposureRoute` mixup in `IntravenousDrugUse` and `NicotineUse`
- Fixed incorrect paths in `Ratio`
- `Numerator` and `Denominator` paths were missing the `Quantity` subpath in their constraints
- Trimmed lots of trailing whitespace (side-effect of editing …
=> Flux-related Changes

.travis.yml
It turns out that bash string comparison cares about string color. This puts up a fix to the `.travis.yml` to strip the string color from the `grep` output.
=> Remove color from error output

spec/ig-breast-config.json, spec/ig-odh-config.json
Breast Cancer config changes:
- Change "Release 2" to "Release 1" to match ballot desktop
- Change "Draft for Comment" to "Draft for Comment 2"
- Change NPM name to "hl7.fhir.us.breastcancer" per Grahame's request
Occupational Data for Health:
- Change project name to match Ballot Desktop name
- Change shorthand to ODH
- Change URLs to canonical forms assigned by HL7
- Change NPM name to "hl7.fhir.us.odh" per HL7
- Change version to 1.0.0
=> Updates to BC and ODH configs

spec/ig-breast-config.json, spec/ig-odh-config.json
Occupational Data for Health:
- Change project name to match Ballot Desktop name
- Change shorthand to ODH
- Change URLs to canonical forms assigned by HL7
- Added NPM name
- Added version
Breast Cancer config changes:
- Change "Release 2" to "Release 1" to match ballot desktop
- Change "Draft for Comment" to "Draft for Comment 2"
- Change NPM name to "hl7.fhir.us.breastcancer" per Grahame's request
- Changed filter strategy to filter on shr.oncology namespace
- Changed publisher info to indicate CIIC
=> Updates to ODH and BC configs

spec/shr_oncology.txt
https://github.com/standardhealth/shr_spec/issues/73
This fix shows in the logical model but remains as 0..0 in the resulting FHIR profile.  Need  @markkramerus or @cmoesel to further investigate if this is a tooling bug or a limitation in FHIR that needs a different class to represent this.
=> Authoring fix for Issue #73 (Ki67 needs to support reference range)

spec/ig-oncocore-config.json, spec/shr_base.txt, spec/shr_base_map_dstu2.txt, spec/shr_base_map_stu3.txt
This PR is needed to get the SHR tooling working correctly, since it depends on `Entry`.  It adds back the `ShrId`, `EntryId`, and `EntryType` fields to `Entry` and removes them from the other places they had been moved to.  It also forces `Entry` ES6 classes to be generated by including `shr.base.Entry` in the config filter.
In the (nearish) future, `Entry` and its fields should be a detail of the implementation -- not a detail of the models.
=> Revert Entry

spec/IndexFolder_Oncocore/terminology.html, spec/ig-breast-config.json, spec/ig-oncocore-config.json, spec/shr_base_finding.txt, spec/shr_base_vs.txt, spec/shr_oncocore_vs.txt
- Replaced MTH/local codes with SCT codes, where possible, in `CancerProgressionVS` and `CancerProgressionEvidenceVS`.
- Replaced local codes in `ExceptionValueVS` with externally defined codes in the data-absent-reason FHIR value set and extended the value set to support "lack of evidence" to complement the `CancerProgressionEvidenceVS` per our discussion with the iCareData team.
- Replaced reference to non-existing `LaboratoryCodeVS` with direct reference to LOINC. The value sets existed in a previous version of `dev` and was throwing an CLI error. It contained all the codes in LOINC.
- Populated terminology page for oncocore IG.
- Made MITRE the publisher for the oncocore IG.
=> Cancer progression and terminology

spec/shr_finding_map_stu3.txt
Fixes the mapping of components to slice at the appropriate place.
NOTE: This works well is shr-fhir-export, but it triggers errors in shr-es6-export.  These errors are currently being investigated.
=> Fix component mapping

spec/cp-mcode.txt
Fix paths in the content profile.  Most fixes fall under one of these categories
- paths used parent type name instead of constrained type name (e.g., SubjectOfRecord instead of PatientSubjectOfRecord)
- paths referred to fields that didn't exist at all (e.g., CancerStageSuffix)
- paths referred to include types (e.g., DNARegionName)
- paths referred to nested fields that weren't mapped (e.g., Person.Race.RaceCode)
This fixes most of the errors reported by my implementation of `must supports` in the FHIR exporter -- but there are still a few more to go.  That said, I think the remaining issues need to be fixed in the exporter, not the CP file.
=> Fix mCODE content profile paths

.travis.yml
There is a known issue w/ ES6 export that cannot be addressed immediately, but should not prevent merging CIMPL source to master.
=> Temporarily disable ES6 for Travis check

spec/obf_allergy_map_r4.txt, spec/obf_encounter.txt, spec/obf_encounter_map_r4.txt, spec/obf_entity_map_r4.txt, spec/obf_finding.txt, spec/obf_finding_map_r4.txt, spec/obf_foundation.txt, spec/obf_foundation_map_dstu2.txt, spec/obf_foundation_map_r4.txt, spec/obf_foundation_map_stu3.txt, spec/obf_medication_map_r4.txt, spec/obf_procedure_map_r4.txt, spec/oncocore_genetics.txt
These updates bring US into the R4 mappings, so mCODE, ODH, and other IGs will be compatible with US Core V3 (the release of US Core that is based on FHIR R4). Certain binding strengths and cardinalities were changed to conform with US Core.
=> Changed R4 mappings to US Core v3 profiles

spec/Examples_mCODE_dstu2/mCODEPrimaryCancerConditionExample01.json, spec/Examples_mCODE_dstu2/mCODEPrimaryCancerConditionExample02_dstu2.json, spec/Examples_mCODE_r4/mCODEPrimaryCancerConditionExample01.json, spec/Examples_mCODE_r4/mCODETNMClinicalDistantMetastasesCategoryExample01.json, spec/Examples_mCODE_r4/mCODETNMClinicalPrimaryTumorCategoryExample01.json, spec/Examples_mCODE_r4/mCODETNMClinicalRegionalNodesCategoryExample01.json, spec/IndexFolder_Oncocore/disease.html, spec/datatype_vs.txt, spec/obf_datatype.txt
- replaced sub-bullets with sub-numbers (MCODE-43);
- fixed PrimaryCancerConditionExamples in R4 and DSTU2 to align with removal of DataOfDiagnosis-extension from the mCODE model;
- added documentation on representing TNM staging category values (MCODE-33).
=> fixed sub-bullets, examples, and documentation

spec/obf_finding_map_r4.txt
Also fixes TNMClinicalCancerStageGroup, TNMPathologicCancerStageGroup, and GenomicsReport FHIR R4 examples.
=> Fixed slice discriminators for DiagnosticReport and Observation

spec/vital_map_r4.txt
Map SystolicPressure / DiastolicPressure to the existing slices in the BP profile.  This mapping uses new capability introduced in SHR-CLI 6.5 and eliminates the duplicated slices that earlier versions produced.
=> Update the BP component mappings

spec/ns-obf/obf-entity.txt, spec/ns-obf/obf-finding.txt, spec/ns-obf/obf-medication.txt, spec/ns-obf/obf-procedure.txt
Note these fixes are R4 and DSTU2-compatible, so we should merge these to `dev6` before attempting to create a DSTU-2 specific branch.
Note that there will be some errors in this code related to code system declaration, which is a fix that we should only apply in a DSTU-2 specific branch. Those changes are included in the branch [dev6-dstu2](https://github.com/standardhealth/shr_spec/tree/dev6-dstu2), which also includes the changes in this PR and compiles cleanly. The `dev6-dstu2` branch is not intended to be merged onto dev6.
=> Agnosticize value set bindings between DSTU2 and R4

spec/ns-obf/obf-allergy.txt, spec/ns-obf/obf-entity.txt
This was causing a crash in the IG publisher when publishing STU3.
It was a pain to chase this down because the IG Publisher just crashed with no helpful output.  This also led me to submit a PR for the IG Publisher that avoids the crash.  See: https://github.com/HL7/fhir-ig-publisher/pull/42
=> Fixes invalid VS URLs to their correct valid values

spec/ig-mcode/ig-mcode-cp.txt
reasonCode and reasonReference elements changed to "MustSupport". It is important to be able to link the procedure to the specific cancer, especially when there is more than one tumor for a patient.
=> Fixed as specified in FHIR-24514
