standardhealth/shr-spec

build.gradle, spec/shr_actors.txt, spec/shr_core.txt, spec/shr_core_vs.txt, spec/shr_identification.txt, spec/shr_identification_vs.txt, spec/shr_lifehistory.txt, spec/shr_metadata.txt, spec/shr_metadata_vs.txt, src/main/antlr/SHRLexer.g4, src/main/antlr/SHRParser.g4
A second take on defining data elements...  This is still evolving (and in fact has already evolved from this).
=> Data Elements - Take 2

spec/shr_actors.txt, spec/shr_allergy.txt, spec/shr_demographics.txt, spec/shr_lifehistory.txt, spec/shr_metadata.txt
Fixes bugs in the text spec itself (typos, missing references, etc).
=> Spec fixes

spec/shr_adverse.txt, spec/shr_adverse_vs.txt, spec/shr_base_map.txt, spec/shr_core_map.txt, spec/shr_core_vs.txt, spec/shr_environment_map.txt, spec/shr_medication.txt, spec/shr_medication_map.txt, spec/shr_medication_vs.txt, spec/shr_problem.txt, spec/shr_problem_vs.txt, spec/shr_vital_map.txt
Various fixes based on new grammar capabilities, new mapping capabilities, and bugs discovered by SHR tooling.
=> Grammar 4.2

spec/shr_procedure.txt
Missed one fix in the last PR...
=> Fix status code system for procedure

spec/shr_condition.txt, spec/shr_familyhistory.txt, spec/shr_oncology.txt, spec/shr_skin.txt
Condition code goes into "SpecificType" attribute, not Value.
=> Fixed error where Conditions had Values

.travis.yml
Travis does not like `&` characters so those are removed.
=> Fix error checking in .travis.yml

.travis.yml
Adds color stripping of `grep` output to fix `.travis.yml`.
=> Strip color from grep output in .travis.yml

spec/shr_oncology.txt, spec/shr_oncology_vs.txt
Resolves #100 plus aligns `StainingIntensityVS` with ASCO/CAP reporting requirements and a few cosmetic updates to element and value set descriptions.
=> Specialize ER and PR

spec/shr_oncology.txt, spec/shr_oncology_vs.txt
=> Minor changes to MorphologyBehavior and BreastCancerHistologicGrade

spec/shr_oncology.txt, spec/shr_oncology_vs.txt
=> Re-apply changes in PR#129 and other ER/PR fixes

spec/IndexFolder_Oncocore/terminology.html, spec/shr_oncocore.txt
Beefed up terminology page and fixed a few issues I noticed on my review.
=> Rute ig review

spec/ig-mcode-cp.txt
Updates to the content profile to align with 1) agreed upon data dictionary content and 2) some level 1 bug fixes from yesterday.
=> mCODE content profile updates

spec/obf_foundation_map_dstu2.txt, spec/obf_foundation_map_r4.txt, spec/obf_foundation_map_stu3.txt
See https://chat.fhir.org/#narrow/stream/197290-cimpl/topic/Possible.20include.20error
=> Update per zulip slicing section in composition

spec/IndexFolder_Oncocore/genomics.html, spec/oncocore_genetics.txt
addressing MCODE-56: https://standardhealthrecord.atlassian.net/browse/MCODE-56.
=> GeneticVariantTested vs. GeneticVariantFound documentation

spec/Examples_mCODE_r4/mCODEGeneticVariantFoundExample01.json, spec/Examples_mCODE_r4/mCODEGenomicsReportExample01.json
=> Fxied GenomicsReport and GeneticVariantFound examples.

spec/ig-mcode-r4-config.json, spec/vital.txt
also fix for MCODE-86: added Provenance to config file.
=> updated vital signs to US Core R4;

spec/IndexFolder_Oncocore/changelog.html, spec/ig-mcode-plist.json, spec/ig-mcode-r4-config.json, spec/obf_assessment.txt, spec/oncocore.txt, spec/oncocore_genetics.txt
Includes:
* Minor tweaks based on IMH feedback
* Fixes to fixes that were not completely applied (that I caught while editing the change log)
* Renamed IG per approved HL7 ballot name
* Updated change log
=> Dev6 mCODE 0.9.1 fixes

.travis.yml
Now `ig-all-r4-config.json`, `ig-all-stu3-config.json`, and `ig-all-dstu2-config.json` are all tested by Travis.
=> Multiple Travis config files

spec/ig-odh/ig-odh-config-backup.json, spec/ig-odh/ig-odh-config.json, spec/ig-odh/ig-odh-plist.json
- Fix history link
- Change publisher to Public Health WG
- Update release descriptions
=> Minor tweaks to ODH configs

spec/ig-odh/LandingPageOccupation.html, spec/ig-odh/ig-odh-config-backup.json, spec/ig-odh/ig-odh-config.json, spec/ig-odh/ig-odh-cp.txt, spec/ig-odh/ig-odh-plist.json, spec/ns-obf-datatype/obf-datatype-vs.txt, spec/ns-obf-datatype/obf-datatype.txt, spec/ns-obf/obf-medication.txt, spec/ns-odh/odh-occupation.txt
Created a ContentProfile and PackageList for Occupational Data for Health (ODH) in anticipation of STU 1 release to HL7.
=> Dev odh no profile move

spec/ig-odh/ig-odh-config.json, spec/ig-odh/ig-odh-cp.txt
=> Dev6 mk odh

spec/ns-onco-core/oncocore-vs.txt
Hi. This commit has the definition of the Histology morphology behavior value set as documented in int-548. Syntax not yet tested. Creating PR for your review since I saw this ticket was added to the sprint. 
Was informed that this wasn't added to the sprint. Leaving PR for discussion if time permits.
=> Histology morphology behavior vsint 548

spec/ig-mcode/IndexFolder-Oncocore/implementation.html
Documentation change addressing issue https://jira.hl7.org/browse/FHIR-24457 (internal tracker item: https://standardhealthrecord.atlassian.net/secure/RapidBoard.jspa?rapidView=13&modal=detail&selectedIssue=INT-593)
=> Added information on provenance

spec/ns-obf/obf-procedure.txt
Fixed as defined in issue. https://jira.hl7.org/browse/FHIR-24520
=> Fix for 24520

spec/ig-mcode/ig-mcode-cp.txt, spec/ig-mcode/ig-mcode-r4-config.json, spec/ns-obf/obf-medication.txt, spec/ns-obf/obf-procedure.txt, spec/ns-onco-core/oncocore-vs.txt, spec/ns-onco-core/oncocore.txt
Constrained cancer-related procedures, added Cancer Related Medication Statement, added clarification for CancerDiseaseStatusEvidenceTypeVS
=> Jira tickets 24513, 24515, 24556

spec/ig-icare/IndexFolder-icare/mapping_guidance.html
Not sure if this is the typical workflow used for new PR's, so let me know if there's anyway I can reconfigure this. Additionally, anyone else planning to merge with dev6 at a later time might need to rebase accordingly - at least that's how STEAM has dealt with feature-branching in the past. Again, let me know if there's anything else I can do to facilitate this fix.
=> Fix treatment plan change language from TreatmentPlanWithReview to CarePlanWithReivew

spec/ig-odh/LandingPageOccupation.html, spec/ig-odh/ig-odh-config.json, spec/ig-odh/ig-odh-cp.txt, spec/ig-odh/ig-odh-plist.json, spec/ns-odh/odh-occupation.txt
=> Changes to ODH for STU1 publication
